In [1]:
# Importing the necessary dependency libraries
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import roc_curve, auc, roc_auc_score
import shap
import imblearn
from imblearn.over_sampling import SMOTE

In [2]:
# Define model performance test functions
def performance_svm(xtrainup,ytrainup,xtrain,ytrain):
    clf.fit(xtrainup,ytrainup)
    # AUC
    auc_scores = roc_auc_score(ytrain, clf.decision_function(xtrain))
    print('auc = ', "%.3f"%auc_scores)
    # accuracy
    from sklearn.metrics import accuracy_score
    accuracy = accuracy_score(ytrain, clf.predict(xtrain))*100
    print('accuracy = ', "%.1f"%accuracy)
    print('------------------------')
    # 混淆矩阵
    import sklearn.metrics as sm
    from sklearn.metrics import confusion_matrix
    matrix = confusion_matrix(ytrain, clf.predict(xtrain), labels=None, sample_weight=None)
    print('混淆矩阵为：')
    print(matrix)
    (tn,fp,fn,tp) = matrix.ravel()
    print('tn=',tn)
    print('fp=',fp)
    print('fn=',fn)
    print('tp=',tp)
    print('------------------------')
    sensitivity = (tp/(tp+fn))*100
    specificity = (tn/(fp+tn))*100
    PPV=tp/(tp+fp)*100
    NPV=tn/(fn+tn)*100
    print(f'PPV = {"%.1f"%PPV}\n({tp}/{(tp+fp)})')
    print(f'NPV = {"%.1f"%NPV}\n({tn}/{(fn+tn)})')
    print(f'sensitivity = {"%.1f"%sensitivity}\n({tp}/{(tp+fn)})')
    print(f'specificity = {"%.1f"%specificity}\n({tn}/{(fp+tn)})')

In [3]:
# Reading data
train = pd.read_csv('F:/Onedrive/JIMMY/Python/Notebook/data_set/inuse/train.csv',encoding='gbk')
test = pd.read_csv('F:/Onedrive/JIMMY/Python/Notebook/data_set/inuse/test.csv',encoding='gbk')
validation = pd.read_csv('F:/Onedrive/JIMMY/Python/Notebook/data_set/inuse/validation_new04.csv',encoding='gbk')

xtrain = train.iloc[:,1:14]
xtest = test.iloc[:,1:14]
xv = validation.iloc[:,1:14]
ytrain = train.iloc[:,-1]
ytest = test.iloc[:,-1]
yv = validation.iloc[:,-1]

# Up-sampling processing
sm = SMOTE(sampling_strategy={1: 2800},random_state=100) 
xtrainup,ytrainup = sm.fit_resample(xtrain,ytrain)

After over-sampling, the number of samples (2800) in class 1 will be larger than the number of samples in the majority class (class #0 -> 1582)


In [4]:
# Model Instantiation
clf = SVC(kernel="linear"
              ,gamma = 1
              ,C= 18
              ,cache_size=10000000
              ,class_weight={1:1})

In [5]:
# Testing the model on the training set
performance_svm(xtrainup,ytrainup,xtrain,ytrain)

auc =  0.907
accuracy =  82.6
------------------------
混淆矩阵为：
[[1263  319]
 [  58  528]]
tn= 1263
fp= 319
fn= 58
tp= 528
------------------------
PPV = 62.3
(528/847)
NPV = 95.6
(1263/1321)
sensitivity = 90.1
(528/586)
specificity = 79.8
(1263/1582)


In [6]:
# Testing the model on the internal validation set
performance_svm(xtrainup,ytrainup,xtest,ytest)

auc =  0.899
accuracy =  82.3
------------------------
混淆矩阵为：
[[526 140]
 [ 25 239]]
tn= 526
fp= 140
fn= 25
tp= 239
------------------------
PPV = 63.1
(239/379)
NPV = 95.5
(526/551)
sensitivity = 90.5
(239/264)
specificity = 79.0
(526/666)


In [7]:
# Testing the model on the external validation set
performance_svm(xtrainup,ytrainup,xv,yv)

auc =  0.870
accuracy =  74.4
------------------------
混淆矩阵为：
[[446 186]
 [ 36 199]]
tn= 446
fp= 186
fn= 36
tp= 199
------------------------
PPV = 51.7
(199/385)
NPV = 92.5
(446/482)
sensitivity = 84.7
(199/235)
specificity = 70.6
(446/632)
